name: Python Security Check

on: [push, pull_request]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Ustawienie wersji Pythona
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # zmień na wersję Pythona używaną w projekcie

    # Instalacja zależności
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Używanie Snyk do sprawdzania zależności
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
